/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { IRenderItemProps } from "./components/wc-fixed-length-list/wc-fixed-length-list";
import { VNode } from "@stencil/core";
export { IRenderItemProps } from "./components/wc-fixed-length-list/wc-fixed-length-list";
export { VNode } from "@stencil/core";
export namespace Components {
    interface WcFixedLengthList {
        "itemHeight": number;
        "numItems": number;
        "renderItem": (props: IRenderItemProps) => VNode;
        "windowHeight": number;
    }
}
declare global {
    interface HTMLWcFixedLengthListElement extends Components.WcFixedLengthList, HTMLStencilElement {
    }
    var HTMLWcFixedLengthListElement: {
        prototype: HTMLWcFixedLengthListElement;
        new (): HTMLWcFixedLengthListElement;
    };
    interface HTMLElementTagNameMap {
        "wc-fixed-length-list": HTMLWcFixedLengthListElement;
    }
}
declare namespace LocalJSX {
    interface WcFixedLengthList {
        "itemHeight"?: number;
        "numItems"?: number;
        "renderItem"?: (props: IRenderItemProps) => VNode;
        "windowHeight"?: number;
    }
    interface IntrinsicElements {
        "wc-fixed-length-list": WcFixedLengthList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "wc-fixed-length-list": LocalJSX.WcFixedLengthList & JSXBase.HTMLAttributes<HTMLWcFixedLengthListElement>;
        }
    }
}
